# Generated by Django 5.0.7 on 2024-07-23 09:23

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
import feelapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, unique=True)),
                ("content", models.TextField()),
                (
                    "image_blog",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=feelapp.models.blog_image_upload_path,
                    ),
                ),
                (
                    "author",
                    models.CharField(blank=True, default="", max_length=255, null=True),
                ),
                (
                    "meta_title",
                    models.CharField(blank=True, default="", max_length=255, null=True),
                ),
                (
                    "meta_description",
                    models.TextField(blank=True, default="", null=True),
                ),
                (
                    "meta_keywords",
                    models.CharField(blank=True, default="", max_length=255, null=True),
                ),
                ("slug", models.SlugField(unique=True)),
                (
                    "hashtags",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=200),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("read_time", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="CategoryModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("priority", models.IntegerField(default=0)),
                (
                    "image_url",
                    models.ImageField(
                        blank=True,
                        default="",
                        null=True,
                        upload_to=feelapp.models.category_image_upload_path,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="HeroOffer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=feelapp.models.national_hero_offer_image
                    ),
                ),
                ("priority", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="Services",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("service_name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField()),
                ("price", models.FloatField()),
                ("discount", models.FloatField()),
                ("gender", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("service_time", models.CharField(max_length=255)),
                (
                    "categories",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="feelapp.categorymodel",
                    ),
                ),
            ],
        ),
    ]
