# Generated by Django 5.0.7 on 2024-07-30 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feelapp", "0003_brandandproduct_brandimage"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="service_items/"
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="hairservice",
            name="gender",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="massageservice",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("male", "Male"), ("female", "Female")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="unisexservice",
            name="gender",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
