# Generated by Django 5.0.7 on 2024-07-30 10:01

import django.db.models.deletion
import feelapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feelapp", "0004_serviceitem_alter_hairservice_gender_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BrandAndProductMulImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        default="",
                        null=True,
                        upload_to=feelapp.models.brand_mul_image_upload_path,
                    ),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mul_images",
                        to="feelapp.brandandproduct",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="BrandImage",
        ),
    ]
