# Generated by Django 5.0.7 on 2024-07-30 11:44

import django.utils.timezone
import feelapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feelapp", "0005_brandandproductmulimage_delete_brandimage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hairservice",
            name="time",
        ),
        migrations.RemoveField(
            model_name="massageservice",
            name="time",
        ),
        migrations.RemoveField(
            model_name="unisexservice",
            name="time",
        ),
        migrations.AddField(
            model_name="brandandproduct",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="hairservice",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="hairservice",
            name="service_time",
            field=models.JSONField(
                blank=True, default=feelapp.models.default_hairservice_time, null=True
            ),
        ),
        migrations.AddField(
            model_name="massagecategory",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="massageservice",
            name="service_time",
            field=models.JSONField(
                blank=True,
                default=feelapp.models.default_massageservice_time,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="serviceitem",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="unisexcategory",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="unisexservice",
            name="service_time",
            field=models.JSONField(
                blank=True, default=feelapp.models.default_unisexservice_time, null=True
            ),
        ),
        
    ]
