# Generated by Django 5.0.7 on 2024-07-30 11:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feelapp", "0006_remove_hairservice_time_remove_massageservice_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="haircategory",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
