# Generated by Django 5.0.7 on 2024-07-31 14:44

import feelapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feelapp", "0009_brandandproduct_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="herooffer",
            name="mobile_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=feelapp.models.national_hero_offer_image,
            ),
        ),
        migrations.AlterField(
            model_name="herooffer",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=feelapp.models.national_hero_offer_image,
            ),
        ),
    ]
