# Generated by Django 5.0.7 on 2024-07-31 14:45

import feelapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feelapp", "0010_herooffer_mobile_image_alter_herooffer_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="herooffer",
            name="mobile_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=feelapp.models.national_mobile_hero_offer_image,
            ),
        ),
    ]
