# Generated by Django 5.0.7 on 2024-08-05 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feelapp", "0011_alter_herooffer_mobile_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="serviceitem",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="service_logo/"),
        ),
    ]
