# Generated by Django 5.0.7 on 2024-08-05 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feelapp", "0012_serviceitem_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="brandandproduct",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="service_logo/"),
        ),
    ]
