# Generated by Django 5.0.4 on 2024-08-08 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("feelapp", "0014_customer_productservice"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productservice",
            name="product_name",
        ),
        migrations.RemoveField(
            model_name="productservice",
            name="product_price",
        ),
    ]
