# Generated by Django 5.0.7 on 2024-08-12 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feelapp", "0015_remove_productservice_product_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="categorymodel",
            name="slug",
            field=models.SlugField(default="", max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name="categorymodel",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("deactive", "Deactive")],
                default="active",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="SubcategoryModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="feelapp.categorymodel",
                    ),
                ),
            ],
        ),
    ]
