# Generated by Django 5.0.7 on 2024-08-12 07:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feelapp", "0016_categorymodel_slug_categorymodel_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subcategorymodel",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
