# Generated by Django 5.0.7 on 2024-08-12 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feelapp", "0017_subcategorymodel_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="subcategorymodel",
            name="priority",
            field=models.IntegerField(default=0),
        ),
    ]
