# Generated by Django 5.0.7 on 2024-08-12 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feelapp", "0019_childcategorymodel"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="services",
            name="discount",
        ),
        migrations.RemoveField(
            model_name="services",
            name="service_time",
        ),
        migrations.AddField(
            model_name="services",
            name="childcategory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="feelapp.childcategorymodel",
            ),
        ),
        migrations.AddField(
            model_name="services",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="services/"),
        ),
        migrations.AddField(
            model_name="services",
            name="priority",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="services",
            name="subcategory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="feelapp.subcategorymodel",
            ),
        ),
        migrations.AlterField(
            model_name="services",
            name="categories",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="feelapp.categorymodel",
            ),
        ),
    ]
