# Generated by Django 5.0.7 on 2024-08-12 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feelapp", "0020_remove_services_discount_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="services",
            name="gender",
        ),
        migrations.AddField(
            model_name="categorymodel",
            name="catid",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="childcategorymodel",
            name="childid",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="services",
            name="servid",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="services",
            name="status",
            field=models.CharField(
                choices=[("true", "True"), ("false", "False")],
                default="",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="subcategorymodel",
            name="subid",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="categorymodel",
            name="slug",
            field=models.SlugField(
                default="", editable=False, max_length=255, unique=True
            ),
        ),
    ]
