# Generated by Django 5.0.7 on 2024-08-15 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feelapp", "0021_remove_services_gender_categorymodel_catid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="services",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
