# Generated by Django 5.0.7 on 2024-08-16 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feelapp", "0022_alter_services_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="birth_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
