# Generated by Django 5.0.7 on 2024-08-16 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feelapp", "0023_alter_customer_birth_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="serviceitem",
            name="categories",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="feelapp.categorymodel",
            ),
        ),
    ]
