# Generated by Django 5.0.7 on 2024-08-22 06:38

import django.utils.timezone
import feelapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feelapp", "0024_serviceitem_categories"),
    ]

    operations = [
        migrations.CreateModel(
            name="Galleryimage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=50, null=True)),
                ("image", models.ImageField(upload_to=feelapp.models.gallery_image)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
